#============
# NametagEdit
#============

# If enabled, this will remove any formatting created in the death messages by prefixes / suffixes
# Do not set this to true if you already have a plugin that changes death messages
DeathMessageEnabled: false

# If enabled, this will remove any formatting created in the tab list by prefixes / suffixes
# Do not set this to true if you already have a plugin that changes the tab list
TabListEnabled: false

# If enabled, this plugin will check for updates when a operator logs in.
CheckForUpdates: false

# If enabled, this plugin will not print 'Setting prefix/suffix' information in the console
ConsolePrintEnabled: false

# If enabled, this plugin will send small data MCStats.org.
MetricsEnabled: true
